### ISSUE TITLE
Timer isn't working for me

### ISSUE THREAD

**Issue by FairGames** [twinysam/BrexitCountdown2019#1]
Hello, i can't setup the timer.

**Comment by twinysam** [comment]
Hello. What do you mean? The timer in the example has ended, it counted down to a date in 2020.

**Comment by FairGames** [comment]
yea, I've changed time for 2023, but it says that timer has ended.
![image](https://user-images.githubusercontent.com/96260907/212068804-543d68bd-dd3c-401a-a603-6a7106223026.png)

**Comment by twinysam** [comment]
I just tested it and it works fine. 
![image](https://user-images.githubusercontent.com/13908849/212116299-ea6893a3-3e51-4cf7-b546-78183206516b.png)

The latest commits have all the JS code commented out, so if you are not very well versed in HTML/JS, you should try a previous version as your starting point, such as: https://github.com/twinysam/BrexitCountdown2019/blob/22c2d7628121ae62ba3076472396cb78ca6dfdee/index.html

In any case, I don't recommend using this for a countdown website, it's using jQuery and momentJS, both of which are dated dependencies. There are a gazillion other countdown examples out there with vanilla JS
